<?php

namespace CrCms\Foundation\Swoole\Server\Events;

use CrCms\Foundation\Swoole\Server\AbstractServer;
use CrCms\Foundation\Swoole\Server\Contracts\EventContract;

/**
 * Class ReceiveEvent
 * @package CrCms\Foundation\Swoole\Server\Events
 */
class ReceiveEvent extends AbstractEvent implements EventContract
{
    /**
     * @var int
     */
    protected $fd;

    /**
     * @var int
     */
    protected $formId;

    /**
     * @var string
     */
    protected $data;

    /**
     * ReceiveEvent constructor.
     * @param int $fd
     * @param int $fromId
     * @param string $data
     */
    public function __construct(int $fd, int $fromId, string $data)
    {
        $this->fd = $fd;
        $this->formId = $fromId;
        $this->data = $data;
    }

    /**
     * @param AbstractServer $server
     */
    public function handle(AbstractServer $server) : void
    {
        parent::handle($server); // TODO: Change the autogenerated stub
    }
}