<?php

namespace CrCms\Framework\Http\Events;

use CrCms\Server\Server\AbstractServer;
use CrCms\Server\Server\Contracts\EventContract;
use CrCms\Server\Server\Events\AbstractEvent;

/**
 * Class MessageEvent
 * @package CrCms\Framework\Http\Events
 */
class MessageEvent extends AbstractEvent implements EventContract
{
    protected $frame;

    public function __construct($frame)
    {
        $this->frame = $frame;
    }

    public function handle(AbstractServer $server): void
    {
        parent::handle($server); // TODO: Change the autogenerated stub
        echo "receive from {$this->frame->fd}:{$this->frame->data},opcode:{$this->frame->opcode},fin:{$this->frame->finish}\n";
        $server->push($this->frame->fd, "this is server");
        logger('',(array)$this->frame);
    }
}